language: python
sudo: false
python:
  - 3.6
addons:
  apt:
    packages:
      - python-dev
virtalenv:
  system_site_packages: true
script:
  - coverage run -m nose
after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
