name: Build Test Coverage
on: [pull_request, workflow_dispatch]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Python 3.8.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.8.12'
    - name: Update PIP
      run: python -m pip install --upgrade pip
    - name: Install Requirements
      run: pip install -r requirements.txt
    - name: Generate Report
      run: coverage run --source=chip8asm -m unittest
    - name: Codecov
      uses: codecov/codecov-action@v4.2.0
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}