name: Build Test Coverage
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.6.8'
      DISPLAY: :0
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.6.8
    - name: Generate Report
      run: |
        pip install -r requirements.txt
        coverage run -m unittest
    - name: Codecov
      uses: codecov/codecov-action@v1.5.2
